- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: List servers in current project
      openstack.cloud.server_info:
      register: result

    - debug:
        var: result.servers
