- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: List all servers from all projects
      openstack.cloud.server_info:
        all_projects: true
      register: result

    - debug:
        var: result.servers
